container-name-run : "swift-run"
container-name-tools : "swift-tools"
image-name-run : "swiftrun"
image-name-tools: "swifttools"
dockerfile-tools: "Dockerfile-tools"
dockerfile-run: "Dockerfile-run"
build-cmd-debug : "/root/utils/tools-utils.sh debug {{applicationName}} 9090"
build-cmd-run : "/root/utils/tools-utils.sh run {{applicationName}}"
test-cmd : "/root/utils/tools-utils.sh test"
container-path-run : "/root/project"
container-path-tools : "/root/project"
container-port-map : "8080:8080"
container-debug-port-map : "9090:9090"
