container-name : "demo-swift"
run-cmd : "run {{applicationName}}"
build-cmd : "build"
test-cmd : "test"
debug-cmd : "debug {{applicationName}} 9090"
container-src-path : "/root/project"
container-port-map : "8080:8080"
container-debug-port-map : "9090:9090"
