container-name : "demo-swift"
run-cmd : "/root/utils/build-utils.sh run {{applicationName}}"
build-cmd : "/root/utils/build-utils.sh build"
test-cmd : "/root/utils/build-utils.sh test"
debug-cmd : "/root/utils/build-utils.sh debug {{applicationName}} 9090"
# host-src-path needs to be updated as we discussed
# Variable for Conan to substitute
host-src-path : "/Users/clay/Documents/swift/kitura-helloworld-master"
container-src-path : "/root/project"
container-port-map : "8080:8080"
container-debug-port-map : "9090:9090"
